export const GET_DEPARTMENT_CATEGORIES = 'GET_DEPARTMENT_CATEGORIES';
export const GET_DEPARTMENT_CATEGORIES_ERROR = 'GET_DEPARTMENT_CATEGORIES_ERROR';
export const GET_DEPARTMENT_CATEGORIES_SUCCESS = 'GET_DEPARTMENT_CATEGORIES_SUCCESS';


export const getDepartmentCategories = (data) => ({
  type: GET_DEPARTMENT_CATEGORIES,
  payload: data
});
