export const GENERATE_UNIQUE_CART = "GENERATE_UNIQUE_CART";
export const GENERATE_UNIQUE_CART_ERROR = "GENERATE_UNIQUE_CART_ERROR";
export const GENERATE_UNIQUE_CART_SUCCESS = "GENERATE_UNIQUE_CART_SUCCESS";

export const generateUniqueCart = () => ({
  type: GENERATE_UNIQUE_CART
});
